name: Android Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: 'gradle'

      - uses: subosito/flutter-action@v2  # Changed to v2
        with:
          flutter-version: "3.22.2"
          channel: 'stable'
          cache: true

      - name: Flutter upgrade
        run: flutter upgrade --force

      - name: Get dependencies
        run: flutter pub get

      - name: Start APK build
        run: flutter build apk

      - uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
